apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ include "simple-test-apisix.fullname" . }}
spec:
  ingressClassName: apisix
  http:
  - name: rule
    match:
      hosts:
      - {{ .Values.route.host | quote }}
      paths:
      - {{ .Values.route.path | quote }}
    backends:
    - serviceName: {{ include "simple-test-apisix.fullname" . }}
      servicePort: 80


