#helm upgrade apisix apisix/apisix -i -f v3test/values.yaml -n ingress-apisix
apisix:
  apisix:
    admin:
      enabled: true
      ingress:
        enabled: false
   #   credentials:
   #     admin: "test-admin"
    deployment:
      role: traditional
      role_traditional:
        config_provider: yaml
  etcd:
    enabled: false
  ingress-controller:
    enabled: true
    apisix:
      adminService:
        namespace: v3-apisix
        name: apisix-v3-admin
  #    baseURL: http://apisix-admin.ingress-apisix.svc.cluster.local:9180
  #    adminKey: edd1c9f034335f136f87ad84b625c8f1
    config:
      provider:
        type: apisix-standalone
    #  apisix:
    #    adminKey: "test-admin"  # <--- AJOUT
    deployment:
      replicas: 2
    # provider connection, global plugins, and plugin metadata.
    gatewayProxy:
      # -- Controls whether to create a default GatewayProxy custom resource.
      createDefault: true
      # -- Configuration for the GatewayProxy provider connection
      #provider:
      #  controlPlane:
      #    service:
      #      name: apisix-admin
      #      port: 9180
      #    auth:
      #      type: AdminKey
      #      adminKey:
      #        value: "test-admin"